apps:
  - name: api-upside-down
    script: ./index.js
    exec_mode: cluster
    instances: 2
    watch: false
    max_memory_restart: 200M
    # env_prod:
    #   ENVIRONMENT: PRODUCTION
    # env_homolog:
    #   ENVIRONMENT: HOMOLOG